"""Inward-facing Phase 2 ports.

The protocols exchange immutable values and canonical bytes. Implementations
are outside the trust domain and cannot mutate a ``ResearchDossier``.
"""

from __future__ import annotations

from typing import Protocol

from ..domain.entities import OpaqueId, ResearchDossier
from .records import (
    ArtifactRef,
    BudgetLimits,
    BudgetSnapshot,
    CostEstimate,
    JobRecord,
    ModelRequest,
    ModelResult,
    ProposalRecord,
    PricingSnapshot,
    ProviderSchemaPreparation,
    RefinementRoundRecord,
    RunRecord,
    RunStopRecord,
    VerifierContextManifest,
)


class ArtifactStore(Protocol):
    def put(self, data: bytes, *, media_type: str) -> ArtifactRef: ...
    def get(self, content_hash: str) -> bytes: ...
    def exists(self, content_hash: str) -> bool: ...


class ModelGateway(Protocol):
    def prepare(self, request: ModelRequest) -> ProviderSchemaPreparation | None: ...
    def complete(self, request: ModelRequest, preparation: ProviderSchemaPreparation | None = None) -> ModelResult: ...


class DurableWorkspace(Protocol):
    def save_dossier(self, dossier: ResearchDossier) -> str: ...
    def load_dossier(self, dossier_id: OpaqueId) -> ResearchDossier: ...
    def create_run(self, *, run_id: OpaqueId, dossier: ResearchDossier, budget_id: OpaqueId, limits: BudgetLimits, now: str) -> RunRecord: ...
    def get_run(self, run_id: OpaqueId) -> RunRecord: ...
    def set_run_status(self, run_id: OpaqueId, status: str, *, now: str, idempotency_key: str) -> RunRecord: ...
    def budget(self, budget_id: OpaqueId, *, now: str) -> BudgetSnapshot: ...
    def reserve_call(self, budget_id: OpaqueId, *, estimated_input_tokens: int, estimated_output_tokens: int, estimated_cost_microusd: int = 0, now: str) -> BudgetSnapshot: ...
    def record_usage(self, budget_id: OpaqueId, *, input_tokens: int, output_tokens: int, cost_microusd: int, now: str) -> BudgetSnapshot: ...
    def enqueue_job(self, *, job_id: OpaqueId, run_id: OpaqueId, kind: str, idempotency_key: str, payload_hash: str, max_attempts: int, deadline_at: str, now: str, round_index: int = 1) -> JobRecord: ...
    def claim_job(self, *, run_id: OpaqueId, kind: str, worker_id: str, lease_until: str, now: str, round_index: int | None = None) -> JobRecord | None: ...
    def finish_job(self, job_id: OpaqueId, *, worker_id: str, status: str, result_hash: str | None, now: str, idempotency_key: str) -> JobRecord: ...
    def list_jobs(self, run_id: OpaqueId) -> tuple[JobRecord, ...]: ...
    def recover_jobs(self, *, now: str) -> tuple[JobRecord, ...]: ...
    def commit_proposal(self, proposal: ProposalRecord, *, job_id: OpaqueId, worker_id: str, now: str, event_key: str) -> ProposalRecord: ...
    def list_proposals(self, run_id: OpaqueId) -> tuple[ProposalRecord, ...]: ...
    def save_manifest(self, manifest: VerifierContextManifest, *, canonical_json: str, now: str) -> VerifierContextManifest: ...
    def get_manifest(self, run_id: OpaqueId, *, round_index: int | None = None) -> VerifierContextManifest: ...
    def list_manifests(self, run_id: OpaqueId) -> tuple[VerifierContextManifest, ...]: ...
    # ADR-0041 bounded refinement rounds.
    def reserve_refinement_round(self, budget_id: OpaqueId, *, round_index: int, now: str) -> BudgetSnapshot: ...
    def record_refinement_round(self, record: RefinementRoundRecord, *, now: str) -> RefinementRoundRecord: ...
    def list_refinement_rounds(self, run_id: OpaqueId) -> tuple[RefinementRoundRecord, ...]: ...
    def record_run_stop(self, record: RunStopRecord, *, now: str) -> RunStopRecord: ...
    def get_run_stop(self, run_id: OpaqueId) -> RunStopRecord | None: ...
    def record_model_call(self, *, call_id: OpaqueId, run_id: OpaqueId, purpose: str, request_hash: str, result_hash: str | None, result: ModelResult, now: str, idempotency_key: str) -> None: ...
    def save_pricing_snapshot(self, snapshot: PricingSnapshot, *, canonical_json: str, now: str) -> PricingSnapshot: ...
    def save_live_run_configuration(self, *, run_id: OpaqueId, configuration_id: OpaqueId, schema_version: str, provider: str, model_identifier: str, pricing_snapshot_id: OpaqueId, content_hash: str, canonical_json: str, now: str, role: str = "proposer") -> None: ...
    def record_cost_estimate(self, estimate: CostEstimate, *, now: str) -> CostEstimate: ...
    def append_event(self, *, event_id: OpaqueId, aggregate_id: OpaqueId, event_type: str, payload_json: str, now: str, idempotency_key: str) -> None: ...
    def timeline(self, aggregate_id: OpaqueId) -> tuple[dict[str, object], ...]: ...
