"""A bibliography entry exists if and only if an acquisition record backs it.

There is no free-text path into ``refs.bib`` and no model in the path. Closure
runs in both directions: a cited key with no entry is a refusal, and an entry no
block cites is also a refusal, because an uncited bibliography implies reading
that did not happen.

``mathlib_declaration`` citations deliberately produce no entry. The pinned
commit *is* the citation, and inventing a bib entry for a library declaration
would make a machine-resolvable reference look like a literature one.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping

from .errors import PublicationValidationError
from .latexsafe import escape_prose
from .manuscript import Manuscript

_CONTAINER_FIELD = {
    "article": "journal",
    "inproceedings": "booktitle",
    "book": "publisher",
    "misc": "howpublished",
    "unpublished": "note",
}


@dataclass(frozen=True, slots=True)
class BibliographyEntry:
    key: str
    entry_type: str
    source_id: str
    fields: tuple[tuple[str, str], ...]

    def render(self) -> str:
        body = ",\n".join(f"  {name} = {{{value}}}" for name, value in self.fields)
        return f"@{self.entry_type}{{{self.key},\n{body}\n}}"


def bib_key(source_id: str) -> str:
    return source_id.replace(".", ":")


def cited_ids(manuscript: Manuscript) -> tuple[str, ...]:
    used: list[str] = []
    for block in manuscript.blocks.values():
        for citation_id in block.get("citations", ()):
            used.append(str(citation_id))
    for claim in manuscript.claims.values():
        for citation_id in claim["citations"]:
            used.append(str(citation_id))
        for citation_id in claim["derivation"]["citations"]:
            used.append(str(citation_id))
        if claim["original_problem_citation_id"] is not None:
            used.append(str(claim["original_problem_citation_id"]))
    return tuple(sorted(set(used)))


def build_bibliography(manuscript: Manuscript) -> tuple[BibliographyEntry, ...]:
    used = cited_ids(manuscript)
    entries: dict[str, BibliographyEntry] = {}
    for citation_id in used:
        citation: Mapping[str, Any] = manuscript.citations[citation_id]
        if citation["citation_class"] != "source_record":
            continue
        source_id = str(citation["source_id"])
        source = manuscript.sources[source_id]
        bibliographic = source["bibliographic"]
        entry_type = str(bibliographic["entry_type"])
        fields: list[tuple[str, str]] = [
            ("author", escape_prose(str(bibliographic["author"]), f"{source_id}.author")),
            ("title", escape_prose(str(bibliographic["title"]), f"{source_id}.title")),
            (
                _CONTAINER_FIELD[entry_type],
                escape_prose(str(bibliographic["container"]), f"{source_id}.container"),
            ),
            ("year", str(bibliographic["year"])),
            ("file", escape_prose(str(bibliographic["identifier"]), f"{source_id}.identifier")),
            ("addendum", f"content hash {source['content_hash']}"),
        ]
        entries[source_id] = BibliographyEntry(
            key=bib_key(source_id), entry_type=entry_type, source_id=source_id,
            fields=tuple(fields),
        )
    for source_id in manuscript.sources:
        if source_id not in entries:
            raise PublicationValidationError(
                "bibliography_entry_uncited",
                f"source {source_id} has a record but no block or claim cites it; an uncited "
                "bibliography implies reading that did not happen",
            )
    return tuple(entries[key] for key in sorted(entries))


def render_bibliography(entries: tuple[BibliographyEntry, ...]) -> str:
    header = (
        "% Generated by the ADR-0036 publication projection.\n"
        "% Every entry below is derived from one acquisition record carrying a content\n"
        "% hash, an authority, and a rights outcome permitting publication. There is no\n"
        "% free-text path into this file and no model in the path.\n"
    )
    return header + "\n" + "\n\n".join(entry.render() for entry in entries) + "\n"


def verify_citation_closure(
    manuscript: Manuscript, entries: tuple[BibliographyEntry, ...], cite_keys: tuple[str, ...]
) -> None:
    known = {entry.key for entry in entries}
    for key in cite_keys:
        if key not in known:
            raise PublicationValidationError(
                "citation_not_in_bibliography", f"\\cite{{{key}}} has no bibliography entry"
            )
    for entry in entries:
        if entry.key not in set(cite_keys):
            raise PublicationValidationError(
                "bibliography_entry_uncited", f"{entry.key} is never cited in the document"
            )
