"""Deterministic projection of a manuscript record set into ``paper.tex``.

Three properties are mechanical rather than conventional.

**Ledger closure.** ``paper.tex`` is exactly the frozen template plus the
concatenation of the ledger's blocks. Every block carries at least one record
reference, so a block cannot reach the document without appearing in the ledger,
and cannot appear in the ledger without a reference. ``verify_ledger_closure``
recomputes the concatenation and compares bytes.

**Computed environments.** No manuscript field names an environment. Every claim
is classified by :mod:`evidence`, and every classification is reported in the
document beside the claim.

**No clock, no randomness, no environment.** The document hash is a function of
the manuscript alone, so it is stable across calls and across processes.

The template carries zero manuscript data, which is what makes its hash a
meaningful constant. One consequence is worth stating: the document cannot
contain its own hash, so ``document_hash`` lives in ``MANIFEST.json`` and the
in-document provenance appendix carries the manuscript and template hashes only.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping

from .bibliography import (
    BibliographyEntry,
    bib_key,
    build_bibliography,
    verify_citation_closure,
)
from .errors import PublicationValidationError
from .evidence import EVIDENCE_CLASSES, EvidenceClassification, classify_claim
from .latexsafe import escape_prose, validate_verbatim
from .manuscript import Manuscript
from .serialization import canonical_hash, text_hash
from ..novelty import load_recheck

TEMPLATE_HEAD = r"""% Generated by the ADR-0036 publication projection. Do not edit.
%
% This file is a projection of a content-hashed record set. The records are the
% artifact of record; this file is regenerable from them, and the PDF is a build
% product of this file. Nothing flows back: a hand edit here is detectable from
% MANIFEST.json and is not a supported operation.
\documentclass[11pt,a4paper]{article}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage[hidelinks]{hyperref}
% The frozen Lean-source display currently admits this one Unicode connective.
% Map it explicitly so pdfLaTeX does not depend on a Unicode math package.
\DeclareUnicodeCharacter{2227}{\ensuremath{\wedge}}
% Byte-reproducible output: no creation timestamp, no trailer id, no file id.
% SOURCE_DATE_EPOCH and FORCE_SOURCE_DATE are set by the typeset driver.
\ifdefined\pdfsuppressptexinfo\pdfsuppressptexinfo=-1\fi
\ifdefined\pdftrailerid\pdftrailerid{}\fi
\theoremstyle{plain}
\newtheorem{adatheorem}{Theorem}
\newtheorem{adaproposition}[adatheorem]{Proposition}
\newtheorem{adaconjecture}[adatheorem]{Conjecture}
\newcommand{\adaprovenance}[1]{%
  \par\smallskip\noindent{\footnotesize\textsf{Provenance.} #1}\par}
\newcommand{\adastatusblock}[1]{%
  \begin{center}\fbox{\parbox{0.92\linewidth}{\small #1}}\end{center}}
\newcommand{\adaleanlabel}[1]{%
  \par\smallskip\noindent{\footnotesize\textsf{Checked Lean statement} (#1):}\par}
\newcommand{\adaformalartifact}[2]{%
  \par\smallskip\noindent{\footnotesize\textsf{Formal artifact.} #1; \href{run:#2}{\nolinkurl{#2}}}\par}
\begin{document}
"""

TEMPLATE_TAIL = r"""\end{document}
"""

ADAIvy_GITHUB_URL = "https://github.com/jketts/AdaIvy"

TEMPLATE_HASH = canonical_hash({"head": TEMPLATE_HEAD, "tail": TEMPLATE_TAIL})


@dataclass(frozen=True, slots=True)
class LedgerBlock:
    block_id: str
    origin: str
    record_refs: tuple[str, ...]
    tex: str

    @property
    def block_hash(self) -> str:
        return text_hash(self.tex)


@dataclass(frozen=True, slots=True)
class RenderedDocument:
    manuscript_id: str
    manuscript_hash: str
    template_hash: str
    document_hash: str
    tex: str
    ledger: tuple[LedgerBlock, ...]
    classifications: tuple[EvidenceClassification, ...]
    bibliography: tuple[BibliographyEntry, ...]
    cite_keys: tuple[str, ...]
    statistics: Mapping[str, Any]


def _texttt(value: str) -> str:
    return r"\texttt{" + escape_prose(value, "identifier") + "}"


def _refs(refs: tuple[str, ...] | list[str]) -> str:
    return ", ".join(_texttt(str(ref)) for ref in sorted(set(str(item) for item in refs)))


def lean_artifact_filename(claim: Mapping[str, Any]) -> str:
    artifact = claim["lean_artifact"]
    if artifact is None:
        raise PublicationValidationError("lean_artifact_missing", str(claim["claim_id"]))
    return str(artifact["declaration_name"]).replace(".", "_").replace("'", "_") + ".lean"


def _citation_text(manuscript: Manuscript, citation_id: str) -> tuple[str, tuple[str, ...]]:
    citation = manuscript.citations[citation_id]
    if citation["citation_class"] == "source_record":
        key = bib_key(str(citation["source_id"]))
        passage_id = citation["passage_id"]
        if passage_id is None:
            return r"\cite{" + key + "}", (key,)
        source = manuscript.sources[str(citation["source_id"])]
        anchor = next(
            str(passage["anchor"])
            for passage in source["passages"]
            if passage["passage_id"] == passage_id
        )
        return r"\cite[" + escape_prose(anchor, "citation.anchor") + "]{" + key + "}", (key,)
    if citation["citation_class"] == "mathlib_declaration":
        commit = str(citation["mathlib_commit"])[:12]
        return (
            _texttt(str(citation["declaration"])) + " (mathlib " + _texttt(commit) + ")",
            (),
        )
    raise PublicationValidationError(
        "folklore_citation_in_prose",
        f"citation {citation_id} is unrecorded background and has no rendered form",
    )


def _prose(manuscript: Manuscript, block: Mapping[str, Any]) -> tuple[str, tuple[str, ...]]:
    parts: list[str] = []
    for run in block["runs"]:
        if run["t"] == "text":
            parts.append(escape_prose(str(run["v"]), "run"))
        else:
            parts.append("$" + str(run["v"]) + "$")
    keys: list[str] = []
    rendered: list[str] = []
    for citation_id in block["citations"]:
        text, citation_keys = _citation_text(manuscript, str(citation_id))
        rendered.append(text)
        keys.extend(citation_keys)
    body = "".join(parts)
    if rendered:
        body += " [" + "; ".join(rendered) + "]"
    return body + "\n\n", tuple(keys)


def _claim(
    manuscript: Manuscript, block: Mapping[str, Any]
) -> tuple[str, tuple[str, ...], EvidenceClassification]:
    claim_id = str(block["claim_id"])
    claim = manuscript.claims[claim_id]
    classification = classify_claim(manuscript, claim_id)
    artifact = claim["lean_artifact"]
    if classification.evidence_class != "proposal" and artifact is None:
        raise PublicationValidationError(
            "solved_claim_without_lean_artifact",
            f"claim {claim_id} renders as {classification.evidence_class} but has no Lean artifact",
        )
    if (
        classification.evidence_class != "proposal"
        and claim["original_problem_citation_id"] is None
    ):
        raise PublicationValidationError(
            "solved_claim_without_original_problem_citation",
            f"claim {claim_id} is solved but does not cite the original problem",
        )
    if (
        classification.evidence_class != "proposal"
        and claim["derivation"]["status"] != "included"
    ):
        raise PublicationValidationError(
            "solved_claim_without_derivation",
            f"claim {claim_id} is solved but has no auditable derivation",
        )
    if classification.evidence_class == "kernel_checked_theorem":
        if artifact is None or artifact["verification_status"] != "kernel_checked":
            raise PublicationValidationError(
                "theorem_without_kernel_checked_artifact",
                f"claim {claim_id} cannot render as a theorem without a kernel-checked artifact",
            )
    lines = [rf"\begin{{{classification.environment}}}[record {_texttt(claim_id)}]"]
    lines.append(escape_prose(str(claim["prose_statement"]), f"{claim_id}.prose_statement"))
    lines.append(r"\begin{equation*}")
    lines.append(str(claim["latex_statement"]))
    lines.append(r"\end{equation*}")
    keys: list[str] = []
    provenance = [
        f"Evidence class {_texttt(classification.evidence_class)}: {escape_prose(classification.reason, 'reason')}.",
        f"Records: {_refs(classification.record_refs)}.",
        "Representation " + _texttt(str(claim["representation_id"]))
        + " is " + _texttt(str(claim["representation_status"])) + ".",
    ]
    if claim["certificate_role"] is not None:
        provenance.append(
            "The certificate is offered as " + _texttt(str(claim["certificate_role"])) + "."
        )
    if classification.approved_axioms:
        provenance.append(
            "Approved axioms: "
            + ", ".join(_texttt(axiom) for axiom in classification.approved_axioms)
            + "."
        )
    if classification.unapproved_assumptions:
        provenance.append(
            "Unapproved assumptions: "
            + ", ".join(_texttt(name) for name in classification.unapproved_assumptions)
            + "."
        )
    rendered: list[str] = []
    for citation_id in claim["citations"]:
        text, citation_keys = _citation_text(manuscript, str(citation_id))
        rendered.append(text)
        keys.extend(citation_keys)
    if rendered:
        provenance.append("Background: " + "; ".join(rendered) + ".")
    original_problem = claim["original_problem_citation_id"]
    if original_problem is not None:
        problem_text, problem_keys = _citation_text(manuscript, str(original_problem))
        provenance.append("Original problem: " + problem_text + ".")
        keys.extend(problem_keys)
    lines.append(r"\adaprovenance{" + " ".join(provenance) + "}")
    lines.append(rf"\end{{{classification.environment}}}")
    authorship = claim["authorship"]
    if authorship["ai_generated"] is True:
        lines.append(
            r"\noindent{\footnotesize\textsf{Contribution.} This result was AI-generated by "
            + escape_prose(str(authorship["generator"]), f"{claim_id}.authorship.generator")
            + r".}\par"
        )
    derivation = claim["derivation"]
    lines.append(r"\paragraph{Auditable derivation.}")
    lines.append(escape_prose(str(derivation["summary"]), f"{claim_id}.derivation.summary"))
    derivation_citations: list[str] = []
    for citation_id in derivation["citations"]:
        text, citation_keys = _citation_text(manuscript, str(citation_id))
        derivation_citations.append(text)
        keys.extend(citation_keys)
    if derivation_citations:
        lines.append("Attribution and source influence: " + "; ".join(derivation_citations) + ".")
    if derivation["status"] == "unavailable":
        lines.append(
            r"\emph{No auditable derivation is available; this is an explicit limitation, "
            r"not an omitted proof.}"
        )
    if artifact is not None:
        relative = "lean/" + lean_artifact_filename(claim)
        status = str(artifact["verification_status"])
        lines.append(r"\adaformalartifact{status " + _texttt(status) + "}{" + relative + "}")
    if claim["lean_statement"] is not None:
        attestation_id = str(claim["attestation_id"]) if claim["attestation_id"] else "unattested"
        lines.append(r"\adaleanlabel{" + _texttt(attestation_id) + "}")
        lines.append(r"\begin{verbatim}")
        lines.append(validate_verbatim(str(claim["lean_statement"]), f"{claim_id}.lean_statement"))
        lines.append(r"\end{verbatim}")
    return "\n".join(lines) + "\n\n", tuple(keys), classification


def _display_math(block: Mapping[str, Any]) -> str:
    caption = escape_prose(str(block["caption"]), f"{block['block_id']}.caption")
    return (
        r"\begin{equation*}" + "\n" + str(block["latex"]) + "\n" + r"\end{equation*}" + "\n"
        + (rf"\noindent{{\footnotesize {caption}}}" + "\n\n" if caption else "\n")
    )


def _certificate_table(manuscript: Manuscript, block: Mapping[str, Any]) -> str:
    certificate = manuscript.certificates[str(block["certificate_id"])]
    rows = [
        ("Case", str(certificate["case_id"])),
        ("Run", str(certificate["run_id"])),
        ("Engine", str(certificate["engine"])),
        ("Arithmetic", str(certificate["arithmetic"])),
        ("Floating point used", "no" if certificate["float_used"] is False else "yes"),
        ("Primal value", str(certificate["primal_value"])),
        ("Dual value", str(certificate["dual_value"])),
        ("Duality gap", str(certificate["gap"])),
        ("Classification", str(certificate["classification"])),
        ("Engine result hash", str(certificate["result_hash"])),
    ]
    body = " \\\\\n".join(
        f"{escape_prose(name, 'row')} & {_texttt(value)}" for name, value in rows
    )
    return (
        r"\begin{center}" + "\n" + r"\begin{tabular}{ll}" + "\n" + r"\hline" + "\n"
        + body + " \\\\\n" + r"\hline" + "\n" + r"\end{tabular}" + "\n"
        + r"\end{center}" + "\n\n"
    )


def _title_block(manuscript: Manuscript) -> str:
    value = manuscript.value
    authors = r" \and ".join(
        escape_prose(str(author["name"]), "author") + r"\thanks{"
        + escape_prose(str(author["role"]), "role") + "}"
        for author in value["authors"]
    )
    return (
        r"\title{" + escape_prose(str(value["title"]), "title") + "}\n"
        + r"\author{" + authors + "}\n"
        + r"\date{}" + "\n" + r"\maketitle" + "\n\n"
    )


def _status_block(
    manuscript: Manuscript, classifications: tuple[EvidenceClassification, ...]
) -> str:
    counts = {name: 0 for name in EVIDENCE_CLASSES}
    for classification in classifications:
        counts[classification.evidence_class] += 1
    theorem_sentence = (
        "This document contains no kernel-checked theorem. Every claim below is either "
        "an exactly certified proposition or a proposal."
        if counts["kernel_checked_theorem"] == 0
        else f"This document contains {counts['kernel_checked_theorem']} kernel-checked theorem(s)."
    )
    approval = manuscript.value["publication_approval"]
    approval_sentence = (
        "No human publication approval record exists. Automated checks alone do not make "
        "this an endorsed AdaIvy result, so this document is a rendered projection and not "
        "an approved publication."
        if approval is None
        else "Publication approval " + _texttt(str(approval["approval_id"]))
        + " is recorded with " + _texttt(str(approval["authority"])) + " authority."
    )
    if approval is None:
        prior_result_sentence = (
            "Prior-result classification: " + _texttt("not_assessed")
            + ". No pre-announcement classification record is attached."
        )
    else:
        announcement = load_recheck(approval["novelty_rechecks"][1])
        prior = announcement.classification()
        prior_result_sentence = (
            "Prior-result classification: " + _texttt(prior.report_classification)
            + "; target resolution status: " + _texttt(prior.target_resolution_status)
            + ". This relationship classification does not create mathematical warrant "
            "or a general novelty assessment."
        )
    toolchain = manuscript.value["toolchain"]
    lines = [
        r"\textbf{Evidence status.} " + theorem_sentence,
        r"\par\smallskip",
        "Claims by computed evidence class: "
        + ", ".join(f"{_texttt(name)} {counts[name]}" for name in EVIDENCE_CLASSES)
        + ".",
        r"\par\smallskip",
        "Environment names are computed from the records that back each claim; no input "
        "field selects one, and every missing record weakens the rendered claim rather "
        "than strengthening it.",
        r"\par\smallskip",
        "Novelty: " + _texttt(str(manuscript.value["novelty"]["status"]))
        + ". Significance: " + _texttt(str(manuscript.value["significance"]["status"]))
        + ". Neither is inferred from any proof status, and no automated assessment of "
        "either exists in this system.",
        r"\par\smallskip",
        prior_result_sentence,
        r"\par\smallskip",
        "Corpus provenance: " + _texttt(str(manuscript.value["corpus_provenance"]))
        + ". " + approval_sentence,
        r"\par\smallskip",
        "Formal backend pinned at Lean " + _texttt(str(toolchain["lean_version"]))
        + " commit " + _texttt(str(toolchain["lean_commit"])[:12])
        + ", mathlib " + _texttt(str(toolchain["mathlib_version"]))
        + " commit " + _texttt(str(toolchain["mathlib_commit"])[:12]) + ".",
        r"Every solved claim has a linked \texttt{.lean} artifact. File creation is not "
        r"formal verification; each link states \texttt{pending}, \texttt{failed}, or "
        r"\texttt{kernel\_checked} from its record.",
    ]
    return r"\adastatusblock{" + "\n" + "\n".join(lines) + "\n}" + "\n\n"


def _abstract_block(manuscript: Manuscript) -> str:
    return (
        r"\begin{abstract}" + "\n"
        + escape_prose(str(manuscript.value["abstract"]), "abstract") + "\n"
        + r"\end{abstract}" + "\n\n"
    )


def _run_disclosure_block(manuscript: Manuscript) -> str:
    disclosure = manuscript.value["run_disclosure"]
    models = "; ".join(
        escape_prose(str(item["provider"]), "run.provider") + " / "
        + _texttt(str(item["model"])) + " ("
        + str(item["calls"]) + " completed call(s))"
        for item in disclosure["models"]
    )
    def shown(key: str, suffix: str = "") -> str:
        item = disclosure[key]
        return "not recorded" if item is None else f"{item}{suffix}"
    return (
        r"\section*{Run disclosure}" + "\n\n"
        + "Recorded model activity: " + models + ". "
        + "Recorded model calls: " + shown("model_calls") + ". "
        + "Recorded external model cost: USD " + shown("cost_usd")
        + " (authorized cap USD " + shown("budget_cap_usd") + "). "
        + "Recorded tokens: " + shown("input_tokens") + " input, "
        + shown("output_tokens") + " output, " + shown("total_tokens") + " total. "
        + "Measurement status: " + _texttt(str(disclosure["measurement_status"])) + ". "
        + escape_prose(str(disclosure["note"]), "run.note") + "\n\n"
    )


def _axioms_appendix(manuscript: Manuscript) -> str:
    if not manuscript.attestations:
        return (
            r"\section*{Appendix A. Axiom dependence}" + "\n\n"
            + "No formal attestation is bound to this document, so no declaration, axiom "
            + "list, or kernel outcome is reportable. Linked Lean artifacts may still be "
            + "present with pending status; file creation is not a kernel result.\n\n"
        )
    rows = []
    for attestation_id in sorted(manuscript.attestations):
        attestation = manuscript.attestations[attestation_id]
        rows.append(
            " & ".join([
                _texttt(str(attestation["declaration_name"])),
                _texttt(str(attestation["outcome"])),
                ", ".join(_texttt(axiom) for axiom in attestation["approved_axioms"]) or "none",
                ", ".join(_texttt(name) for name in attestation["unapproved_assumptions"]) or "none",
            ])
        )
    body = " \\\\\n".join(rows)
    return (
        r"\section*{Appendix A. Axiom dependence}" + "\n\n"
        + "Each row is the recorded output of a kernel check plus its "
        + r"\texttt{\#print axioms} " + "result, against the pinned toolchain named in the "
        + "status block.\n\n"
        + r"\begin{center}" + "\n"
        + r"\begin{tabular}{llll}" + "\n" + r"\hline" + "\n"
        + r"Declaration & Outcome & Approved axioms & Unapproved assumptions \\" + "\n"
        + r"\hline" + "\n" + body + " \\\\\n" + r"\hline" + "\n"
        + r"\end{tabular}" + "\n" + r"\end{center}" + "\n\n"
    )


def _obligations_appendix(manuscript: Manuscript) -> str:
    if not manuscript.obligations:
        return (
            r"\section*{Appendix B. Open obligations}" + "\n\n"
            + "No obligation record exists for this document.\n\n"
        )
    items = []
    for obligation_id in sorted(manuscript.obligations):
        obligation = manuscript.obligations[obligation_id]
        items.append(
            r"\item[" + _texttt(obligation_id) + "] "
            + escape_prose(str(obligation["statement"]), "statement")
            + " Status " + _texttt(str(obligation["status"])) + ". "
            + escape_prose(str(obligation["reason"]), "reason")
        )
    return (
        r"\section*{Appendix B. Open obligations}" + "\n\n"
        + "Background this document relies on but holds no record for appears here rather "
        + "than in the bibliography. An unrecorded reference is an open obligation, not a "
        + "citation.\n\n"
        + r"\begin{description}" + "\n" + "\n".join(items) + "\n" + r"\end{description}" + "\n\n"
    )


def _provenance_appendix(manuscript: Manuscript) -> str:
    return (
        r"\section*{Appendix C. Reproduction}" + "\n\n"
        + "This document is a projection of manuscript "
        + _texttt(manuscript.manuscript_id) + " with content hash "
        + _texttt(manuscript.hash) + ", rendered against template "
        + _texttt(TEMPLATE_HASH) + ". The bundle accompanying this document carries the "
        + "records the projection read, the Lean source for every solved claim, and a "
        + "manifest hashing every file. A document cannot contain its own hash, so the "
        + "rendered document hash and the bundle hash are recorded in "
        + _texttt("MANIFEST.json") + " rather than here.\n\n"
    )


def _bibliography_block(entries: tuple[BibliographyEntry, ...]) -> str:
    if not entries:
        return ""
    widest = max(len(entry.key) for entry in entries)
    items = []
    for entry in entries:
        fields = dict(entry.fields)
        items.append(
            r"\bibitem{" + entry.key + "} "
            + fields.get("author", "")
            + ", \\emph{" + fields.get("title", "") + "}, "
            + ", ".join(
                value for name, value in entry.fields
                if name not in {"author", "title"} and value
            )
            + "."
        )
    return (
        r"\begin{thebibliography}{" + "9" * min(widest, 2) + "}" + "\n"
        + "\n".join(items) + "\n" + r"\end{thebibliography}" + "\n\n"
    )


def _project_footnote() -> str:
    return (
        r"\par\bigskip\noindent\emph{About this project}\footnote{" +
        "AdaIvy is an open-source AI-assisted mathematical research project that keeps "
        "retrieval, computation, formal checking, human review, and publication status "
        "as separate recorded boundaries. Source code and reproducibility materials: "
        r"\url{" + ADAIvy_GITHUB_URL + r"}.}" + "\n\n"
    )


def render_manuscript(manuscript: Manuscript) -> RenderedDocument:
    ledger: list[LedgerBlock] = []
    classifications: list[EvidenceClassification] = []
    cite_keys: list[str] = []
    manuscript_id = manuscript.manuscript_id
    namespace = set(manuscript.record_ids) | {manuscript_id}

    def add(block_id: str, origin: str, refs: tuple[str, ...], tex: str) -> None:
        if not refs:
            raise PublicationValidationError(
                "block_without_record_ref", f"derived block {block_id} carries no record reference"
            )
        for ref in refs:
            if ref not in namespace:
                raise PublicationValidationError(
                    "record_ref_unresolved", f"block {block_id} references {ref!r}"
                )
        ledger.append(LedgerBlock(block_id=block_id, origin=origin, record_refs=refs, tex=tex))

    add("derived.title", "derived", (manuscript_id,), _title_block(manuscript))

    # The status block is emitted here, before any section, and no manuscript
    # field can remove it: it is produced by the renderer rather than read from
    # the sections list. It is appended after classification below, so it is
    # inserted as a placeholder index and rewritten once the classes are known.
    status_index = len(ledger)
    ledger.append(
        LedgerBlock(block_id="derived.status", origin="derived", record_refs=(manuscript_id,), tex="")
    )
    add("derived.abstract", "derived", (manuscript_id,), _abstract_block(manuscript))
    add("derived.run-disclosure", "derived", (manuscript_id,), _run_disclosure_block(manuscript))

    for section in manuscript.value["sections"]:
        section_refs: list[str] = []
        rendered_blocks: list[tuple[str, tuple[str, ...], str]] = []
        for block in section["blocks"]:
            block_id = str(block["block_id"])
            refs = tuple(str(ref) for ref in block["record_refs"])
            section_refs.extend(refs)
            if block["kind"] == "prose":
                tex, keys = _prose(manuscript, block)
                cite_keys.extend(keys)
            elif block["kind"] == "claim":
                tex, keys, classification = _claim(manuscript, block)
                cite_keys.extend(keys)
                classifications.append(classification)
            elif block["kind"] == "display_math":
                tex = _display_math(block)
            else:
                tex = _certificate_table(manuscript, block)
            rendered_blocks.append((block_id, refs, tex))
        heading = (
            r"\section{" + escape_prose(str(section["title"]), "section.title") + "}" + "\n\n"
        )
        add(f"derived.heading.{section['section_id']}", "derived", tuple(section_refs), heading)
        for block_id, refs, tex in rendered_blocks:
            add(block_id, "manuscript", refs, tex)

    ledger[status_index] = LedgerBlock(
        block_id="derived.status", origin="derived",
        record_refs=tuple(sorted({item.claim_id for item in classifications}) or (manuscript_id,)),
        tex=_status_block(manuscript, tuple(classifications)),
    )

    add(
        "derived.appendix.axioms", "derived",
        tuple(sorted(manuscript.attestations)) or (manuscript_id,),
        _axioms_appendix(manuscript),
    )
    add(
        "derived.appendix.obligations", "derived",
        tuple(sorted(manuscript.obligations)) or (manuscript_id,),
        _obligations_appendix(manuscript),
    )
    add("derived.appendix.reproduction", "derived", (manuscript_id,), _provenance_appendix(manuscript))

    entries = build_bibliography(manuscript)
    verify_citation_closure(manuscript, entries, tuple(cite_keys))
    if entries:
        add(
            "derived.bibliography", "derived",
            tuple(sorted(entry.source_id for entry in entries)),
            _bibliography_block(entries),
        )

    add("derived.project-footnote", "derived", (manuscript_id,), _project_footnote())

    tex = TEMPLATE_HEAD + "".join(block.tex for block in ledger) + TEMPLATE_TAIL
    counts = {name: 0 for name in EVIDENCE_CLASSES}
    for classification in classifications:
        counts[classification.evidence_class] += 1
    statistics = {
        "blocks": len(ledger),
        "manuscript_blocks": sum(1 for block in ledger if block.origin == "manuscript"),
        "derived_blocks": sum(1 for block in ledger if block.origin == "derived"),
        "claims": len(classifications),
        "evidence_class_counts": counts,
        "bibliography_entries": len(entries),
        "cite_keys": len(set(cite_keys)),
        "obligations_open": sum(
            1 for obligation in manuscript.obligations.values() if obligation["status"] == "open"
        ),
        "tex_bytes": len(tex.encode("utf-8")),
    }
    document = RenderedDocument(
        manuscript_id=manuscript_id, manuscript_hash=manuscript.hash,
        template_hash=TEMPLATE_HASH, document_hash=text_hash(tex), tex=tex,
        ledger=tuple(ledger), classifications=tuple(classifications), bibliography=entries,
        cite_keys=tuple(sorted(set(cite_keys))), statistics=statistics,
    )
    verify_ledger_closure(document)
    return document


def verify_ledger_closure(document: RenderedDocument) -> None:
    """Refuse a document that is not exactly template plus ledger."""

    for block in document.ledger:
        if not block.record_refs:
            raise PublicationValidationError(
                "block_without_record_ref", f"ledger block {block.block_id} carries no reference"
            )
    recomputed = TEMPLATE_HEAD + "".join(block.tex for block in document.ledger) + TEMPLATE_TAIL
    if recomputed != document.tex:
        raise PublicationValidationError(
            "ledger_closure_broken",
            "the document is not exactly the frozen template plus the ledger blocks",
        )
    if document.document_hash != text_hash(document.tex):
        raise PublicationValidationError(
            "document_hash_mismatch", "the recorded document hash does not cover the document"
        )
    if document.template_hash != TEMPLATE_HASH:
        raise PublicationValidationError(
            "template_hash_mismatch", "the document was rendered against a different template"
        )


def ledger_payload(document: RenderedDocument) -> dict[str, Any]:
    return {
        "manuscript_id": document.manuscript_id,
        "manuscript_hash": document.manuscript_hash,
        "template_hash": document.template_hash,
        "document_hash": document.document_hash,
        "blocks": [
            {
                "block_id": block.block_id,
                "origin": block.origin,
                "record_refs": list(block.record_refs),
                "block_hash": block.block_hash,
                "bytes": len(block.tex.encode("utf-8")),
            }
            for block in document.ledger
        ],
    }
