"""Deterministic projection of a manuscript record set into ``paper.tex``.

Three properties are mechanical rather than conventional.

**Ledger closure.** ``paper.tex`` is exactly the frozen template plus the
concatenation of the ledger's blocks. Every block carries at least one record
reference, so a block cannot reach the document without appearing in the ledger,
and cannot appear in the ledger without a reference. ``verify_ledger_closure``
recomputes the concatenation and compares bytes.

**Computed environments.** No manuscript field names an environment. Every claim
is classified by :mod:`evidence`, and every classification is reported in the
document beside the claim.

**Composed headline.** The displayed title is not a manuscript field. It is
``title_stem`` plus a qualifier computed from the derived reading scope, the
weakest evidence class, the ADR-0059 prior-art classification and the open
obligations tagged ``novelty`` or ``prior_art``. The composition is a ledger
block with resolving record references, so ADR-0036's byte-exact closure covers
the one string that used to sit outside it, and ``verify_headline_closure``
recomputes it from the records and refuses a document whose headline the ledger
does not account for.

**No clock, no randomness, no environment.** The document hash is a function of
the manuscript alone, so it is stable across calls and across processes.

The template carries zero manuscript data, which is what makes its hash a
meaningful constant. One consequence is worth stating: the document cannot
contain its own hash, so ``document_hash`` lives in ``MANIFEST.json`` and the
in-document provenance appendix carries the manuscript and template hashes only.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Mapping

from .bibliography import (
    BibliographyEntry,
    bib_key,
    build_bibliography,
    verify_citation_closure,
)
from .errors import PublicationValidationError
from .evidence import EVIDENCE_CLASSES, EvidenceClassification, classify_claim
from .latexsafe import escape_prose, validate_verbatim
from .manuscript import RESOLUTION_LEXICON, Manuscript, lexicon_hits
from .serialization import canonical_hash, text_hash
from ..novelty import load_recheck

TEMPLATE_HEAD = r"""% Generated by the ADR-0036 publication projection. Do not edit.
%
% This file is a projection of a content-hashed record set. The records are the
% artifact of record; this file is regenerable from them, and the PDF is a build
% product of this file. Nothing flows back: a hand edit here is detectable from
% MANIFEST.json and is not a supported operation.
\documentclass[11pt]{article}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage[hidelinks]{hyperref}
% Allow long identifiers and content hashes to wrap without changing their text.
\def\UrlBreaks{\do\/\do\-\do\.\do\:\do0\do1\do2\do3\do4\do5\do6\do7\do8\do9\do a\do b\do c\do d\do e\do f}
% The frozen Lean-source display currently admits this one Unicode connective.
% Map it explicitly so pdfLaTeX does not depend on a Unicode math package.
\DeclareUnicodeCharacter{2227}{\ensuremath{\wedge}}
\DeclareUnicodeCharacter{00AC}{\ensuremath{\neg}}
\DeclareUnicodeCharacter{2264}{\ensuremath{\leq}}
% Byte-reproducible output: no creation timestamp, no trailer id, no file id.
% SOURCE_DATE_EPOCH and FORCE_SOURCE_DATE are set by the typeset driver.
\ifdefined\pdfsuppressptexinfo\pdfsuppressptexinfo=-1\fi
\ifdefined\pdftrailerid\pdftrailerid{}\fi
% Frozen classic-paper layout, shared by every AdaIvy publication report.
\setlength{\textwidth}{6.35in}
\setlength{\textheight}{8.9in}
\setlength{\oddsidemargin}{0.05in}
\setlength{\evensidemargin}{0.05in}
\setlength{\topmargin}{-0.35in}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.65em}
\setlength{\emergencystretch}{2em}
\theoremstyle{plain}
\newtheorem{adatheorem}{Theorem}
\newtheorem{adaproposition}[adatheorem]{Proposition}
% ADR-0058. The reader meets the qualification in the environment name rather
% than in a footnote they may not reach.
\newtheorem{adaconditional}[adatheorem]{Proposition (convention-relative)}
\newtheorem{adaconjecture}[adatheorem]{Conjecture}
\newcommand{\adaprovenance}[1]{%
  \par\smallskip\begin{sloppypar}\noindent{\footnotesize\textsf{Provenance.} #1}\par\end{sloppypar}}
\newcommand{\adastatusblock}[1]{%
  \begin{center}\fbox{\parbox{0.92\linewidth}{\small #1}}\end{center}}
\newcommand{\adaleanlabel}[1]{%
  \par\smallskip\noindent{\footnotesize\textsf{Checked Lean statement} (#1):}\par}
\newcommand{\adaformalartifact}[2]{%
  \par\smallskip\noindent{\footnotesize\textsf{Formal artifact.} #1; \href{run:#2}{\nolinkurl{#2}}}\par}
\begin{document}
"""

TEMPLATE_TAIL = r"""\end{document}
"""

ADAIvy_GITHUB_URL = "https://github.com/jketts/AdaIvy"

TEMPLATE_HASH = canonical_hash({"head": TEMPLATE_HEAD, "tail": TEMPLATE_TAIL})


#: ADR-0058's derived headline vocabulary, frozen. Every phrase a composed title
#: can carry is in this module. The only manuscript strings that reach the
#: displayed title are ``title_stem`` -- screened against ``RESOLUTION_LEXICON``
#: at load time -- and a subject label mechanically derived from a record
#: identifier and screened against the same lexicon here. There is no field whose
#: value selects a qualifier, and no value that removes one.
RESOLUTION_KIND_PHRASES = {"refutation": "Counterexample to", "proof": "Proof of"}

#: The hedge a reader needs when the records do not close the question. It is
#: added unless *every* input is at its strongest, so the default is hedged.
CANDIDATE_PREFIX = "Candidate "

#: Weakest first is the direction that matters: the qualifier is computed from the
#: weakest claim in the document, never from the best one.
SCOPE_WEAKNESS_ORDER = (
    "unconditional", "convention_relative", "contested_unevaluated", "no_reading_refutes",
)
SCOPE_QUALIFIERS = {
    "unconditional": None,
    "convention_relative": "convention-relative",
    "contested_unevaluated": "some enumerated reading was never evaluated",
    "no_reading_refutes": "no enumerated reading refutes",
}
EVIDENCE_CLASS_QUALIFIERS = {
    "kernel_checked_theorem": None,
    "exact_certificate_proposition": None,
    "convention_relative_proposition": None,
    "proposal": "unresolved on these records",
}
#: ADR-0055 report classifications, mapped to reader-facing words. Only
#: ``no_prior_art_found_under_protocol`` clears the qualifier, and it clears it
#: because a bounded search was actually run and recorded.
PRIOR_ART_QUALIFIERS = {
    "no_prior_art_found_under_protocol": None,
    "prior_art_search_inconclusive": "prior-art search inconclusive",
    "reported_prior_resolution": "a prior resolution is reported",
    "independent_verification": "independent verification of a prior result",
    "extension_of_prior_result": "extension of a prior result",
    "related_to_prior_result": "related to a prior result",
    "prior_art_relationship_unresolved": "prior art relationship unresolved",
}
#: The absent-record case, which must read as weaker than every recorded one.
PRIOR_ART_UNASSESSED = "prior art not assessed"
OBLIGATION_TAG_WORDS = {"novelty": "novelty", "prior_art": "prior-art"}
#: Record-kind prefixes dropped when a subject identifier becomes a reader-facing
#: label. Anything else is kept, so an unrecognised namespace stays visible.
SUBJECT_ID_PREFIXES = frozenset({"problem", "conjecture", "question", "subject", "target"})
#: ADR-0060. "source-faithful" is never in this table: it is earned only when
#: every reading is verbatim-confirmed, and then it is still not said here.
READING_FIDELITY_WORDS = {
    "verbatim_confirmed": "source-verbatim reading",
    "transcribed": "source-transcribed reading",
    "asserted": "source-asserted reading",
}
ENUMERATION_LIMIT_SENTENCE = (
    "A derived scope of unconditional means unconditional over the readings this "
    "record enumerates, never over every reading that exists: the enumeration is "
    "author-supplied, and a contested term nobody recorded is invisible to this "
    "machinery. Scope is also a truth-conditional axis and not a priority axis; "
    "whether an earlier candidate pre-empts a result is a prior-art question, "
    "recorded in the replay table and the prior-art classification."
)


def subject_label(subject_id: str) -> str:
    """A reader-facing name for a subject identifier, derived mechanically.

    ``problem.graffiti-322`` becomes ``Graffiti 322``. The transformation is a
    function of the identifier alone, and the result is screened by
    :func:`compose_headline` against the resolution lexicon, because a subject id
    is the one manuscript string the composed title still quotes.
    """

    parts = [part for part in str(subject_id).split(".") if part]
    if len(parts) > 1 and parts[0] in SUBJECT_ID_PREFIXES:
        parts = parts[1:]
    words = [word for word in re.split(r"[-_.]+", ".".join(parts)) if word]
    label = " ".join(
        word if word[:1].isdigit() else word[:1].upper() + word[1:] for word in words
    )
    return label or str(subject_id)


@dataclass(frozen=True, slots=True)
class Headline:
    """The composed displayed title, and the records that composed it."""

    title_stem: str
    resolution_phrase: str
    qualifiers: tuple[str, ...]
    displayed_title: str
    record_refs: tuple[str, ...]
    derivation: tuple[str, ...]


def compose_headline(
    manuscript: Manuscript, classifications: tuple[EvidenceClassification, ...]
) -> Headline:
    """Compose the displayed title from records. No field selects the qualifier.

    The qualifier is lost only when every input is at its strongest: every
    resolution-typed claim sweeps its readings, no claim sits at ``proposal``, a
    prior-art record says a bounded search found nothing, and no obligation
    tagged ``novelty`` or ``prior_art`` is open. Each of those is a record, and a
    missing record is the weak case rather than the silent one.
    """

    stem = str(manuscript.value["title_stem"])
    resolution_claims = manuscript.resolution_claim_ids()
    if not resolution_claims:
        # Nothing claims to resolve anything, so there is nothing to qualify. The
        # stem itself is still refused at load time if it says otherwise.
        return Headline(
            title_stem=stem, resolution_phrase="", qualifiers=(), displayed_title=stem,
            record_refs=(manuscript.manuscript_id,),
            derivation=("no claim carries a resolution_target, so no resolution is claimed",),
        )

    classes = {item.claim_id: item.evidence_class for item in classifications}
    refs: list[str] = [manuscript.manuscript_id]
    derivation: list[str] = []

    scopes: list[str] = []
    phrases: list[str] = []
    weakest_class = "kernel_checked_theorem"
    for claim_id in resolution_claims:
        claim = manuscript.claims[claim_id]
        target = claim["resolution_target"]
        kind = str(target["kind"])
        label = subject_label(str(target["subject_id"]))
        hits = lexicon_hits(label, RESOLUTION_LEXICON)
        if hits:
            raise PublicationValidationError(
                "resolution_subject_label_asserts_resolution",
                f"claim {claim_id} names subject {target['subject_id']!r}, which reads as "
                f"{list(hits)} in the composed title; the derived qualifier decides how "
                "strong a headline is, and a record identifier may not pre-empt it",
            )
        phrase = RESOLUTION_KIND_PHRASES.get(kind)
        if phrase is None:
            raise PublicationValidationError(
                "resolution_target_kind_unrenderable",
                f"claim {claim_id} resolves its target by {kind!r}, which this projection "
                "has no derived phrase for; an unrenderable kind is a refusal, never a "
                "headline the reader has to guess at",
            )
        phrases.append(f"{phrase} {label}")
        refs.append(claim_id)
        matrix = manuscript.verdict_matrix_for(claim_id)
        if matrix is not None:
            refs.extend([matrix.matrix_id, matrix.convention_id])
        scope = manuscript.derived_scope(claim_id)
        if scope is not None:
            scopes.append(scope)
        # A resolution-typed claim that reaches no section block contributes no
        # classification. It counts as the weakest class rather than the
        # strongest: an undisplayed claim must not buy the headline a rung.
        observed = classes.get(claim_id, EVIDENCE_CLASSES[-1])
        if EVIDENCE_CLASSES.index(observed) > EVIDENCE_CLASSES.index(weakest_class):
            weakest_class = observed

    weakest_scope = (
        max(scopes, key=SCOPE_WEAKNESS_ORDER.index) if scopes else "contested_unevaluated"
    )
    derivation.append(f"weakest derived scope across resolution claims: {weakest_scope}")
    derivation.append(f"weakest evidence class across resolution claims: {weakest_class}")

    qualifiers: list[str] = []
    scope_qualifier = SCOPE_QUALIFIERS[weakest_scope]
    if scope_qualifier:
        qualifiers.append(scope_qualifier)
    class_qualifier = EVIDENCE_CLASS_QUALIFIERS[weakest_class]
    if class_qualifier:
        qualifiers.append(class_qualifier)

    recheck = manuscript.prior_art_recheck()
    if recheck is None:
        qualifiers.append(PRIOR_ART_UNASSESSED)
        derivation.append("prior_art_engagement is null")
    else:
        classification = recheck.classification()
        refs.append(recheck.recheck_id)
        derivation.append(
            f"prior-art classification {classification.report_classification} from "
            f"{recheck.recheck_id}"
        )
        prior_qualifier = PRIOR_ART_QUALIFIERS[classification.report_classification]
        if prior_qualifier:
            qualifiers.append(prior_qualifier)

    open_tags = manuscript.open_obligation_tags() & set(OBLIGATION_TAG_WORDS)
    if open_tags:
        words = " and ".join(OBLIGATION_TAG_WORDS[tag] for tag in sorted(open_tags))
        qualifiers.append(f"open {words} obligations")
        for obligation_id, obligation in sorted(manuscript.obligations.items()):
            if obligation["status"] in {"open", "blocked"} and set(obligation["tags"]) & open_tags:
                refs.append(obligation_id)
        derivation.append(
            "open obligations tagged " + ", ".join(sorted(open_tags))
        )

    hedged = bool(qualifiers) or weakest_class != "kernel_checked_theorem"
    prefix = CANDIDATE_PREFIX if hedged else ""
    resolution_phrase = prefix + " and ".join(dict.fromkeys(phrases))
    displayed = stem + ": " + resolution_phrase
    if qualifiers:
        displayed += " (" + "; ".join(qualifiers) + ")"
    return Headline(
        title_stem=stem, resolution_phrase=resolution_phrase, qualifiers=tuple(qualifiers),
        displayed_title=displayed, record_refs=tuple(dict.fromkeys(refs)),
        derivation=tuple(derivation),
    )


@dataclass(frozen=True, slots=True)
class LedgerBlock:
    block_id: str
    origin: str
    record_refs: tuple[str, ...]
    tex: str

    @property
    def block_hash(self) -> str:
        return text_hash(self.tex)


@dataclass(frozen=True, slots=True)
class RenderedDocument:
    manuscript_id: str
    manuscript_hash: str
    template_hash: str
    document_hash: str
    headline: Headline
    tex: str
    ledger: tuple[LedgerBlock, ...]
    classifications: tuple[EvidenceClassification, ...]
    bibliography: tuple[BibliographyEntry, ...]
    cite_keys: tuple[str, ...]
    statistics: Mapping[str, Any]


def _texttt(value: str) -> str:
    if len(value) > 32 and re.fullmatch(r"[A-Za-z0-9._:/-]+", value):
        return r"\nolinkurl{" + value + "}"
    return r"\texttt{" + escape_prose(value, "identifier") + "}"


def _refs(refs: tuple[str, ...] | list[str]) -> str:
    return ", ".join(_texttt(str(ref)) for ref in sorted(set(str(item) for item in refs)))


def lean_artifact_filename(claim: Mapping[str, Any]) -> str:
    artifact = claim["lean_artifact"]
    if artifact is None:
        raise PublicationValidationError("lean_artifact_missing", str(claim["claim_id"]))
    return str(artifact["declaration_name"]).replace(".", "_").replace("'", "_") + ".lean"


def _citation_text(manuscript: Manuscript, citation_id: str) -> tuple[str, tuple[str, ...]]:
    citation = manuscript.citations[citation_id]
    if citation["citation_class"] == "source_record":
        key = bib_key(str(citation["source_id"]))
        # Passage identity remains enforced by citation closure, but reader-facing
        # prose uses conventional numeric citations. Source and locator details
        # belong to the bibliography record rather than the sentence itself.
        return r"\cite{" + key + "}", (key,)
    if citation["citation_class"] == "mathlib_declaration":
        commit = str(citation["mathlib_commit"])[:12]
        return (
            _texttt(str(citation["declaration"])) + " (mathlib " + _texttt(commit) + ")",
            (),
        )
    raise PublicationValidationError(
        "folklore_citation_in_prose",
        f"citation {citation_id} is unrecorded background and has no rendered form",
    )


def _prose(manuscript: Manuscript, block: Mapping[str, Any]) -> tuple[str, tuple[str, ...]]:
    parts: list[str] = []
    for run in block["runs"]:
        if run["t"] == "text":
            parts.append(escape_prose(str(run["v"]), "run"))
        else:
            parts.append("$" + str(run["v"]) + "$")
    keys: list[str] = []
    rendered: list[str] = []
    for citation_id in block["citations"]:
        text, citation_keys = _citation_text(manuscript, str(citation_id))
        rendered.append(text)
        keys.extend(citation_keys)
    body = "".join(parts)
    if rendered:
        body += " " + ", ".join(dict.fromkeys(rendered))
    return body + "\n\n", tuple(keys)


def _claim(
    manuscript: Manuscript, block: Mapping[str, Any]
) -> tuple[str, tuple[str, ...], EvidenceClassification]:
    claim_id = str(block["claim_id"])
    claim = manuscript.claims[claim_id]
    classification = classify_claim(manuscript, claim_id)
    artifact = claim["lean_artifact"]
    if classification.evidence_class != "proposal" and artifact is None:
        raise PublicationValidationError(
            "solved_claim_without_lean_artifact",
            f"claim {claim_id} renders as {classification.evidence_class} but has no Lean artifact",
        )
    if (
        classification.evidence_class != "proposal"
        and claim["original_problem_citation_id"] is None
    ):
        raise PublicationValidationError(
            "solved_claim_without_original_problem_citation",
            f"claim {claim_id} is solved but does not cite the original problem",
        )
    if (
        classification.evidence_class != "proposal"
        and claim["derivation"]["status"] != "included"
    ):
        raise PublicationValidationError(
            "solved_claim_without_derivation",
            f"claim {claim_id} is solved but has no auditable derivation",
        )
    if classification.evidence_class == "kernel_checked_theorem":
        if artifact is None or artifact["verification_status"] != "kernel_checked":
            raise PublicationValidationError(
                "theorem_without_kernel_checked_artifact",
                f"claim {claim_id} cannot render as a theorem without a kernel-checked artifact",
            )
    lines = [rf"\begin{{{classification.environment}}}[record {_texttt(claim_id)}]"]
    lines.append(escape_prose(str(claim["prose_statement"]), f"{claim_id}.prose_statement"))
    lines.append(r"\begin{equation*}")
    lines.append(str(claim["latex_statement"]))
    lines.append(r"\end{equation*}")
    keys: list[str] = []
    provenance = [
        f"Evidence class {_texttt(classification.evidence_class)}: {escape_prose(classification.reason, 'reason')}.",
        f"Records: {_refs(classification.record_refs)}.",
        "Representation " + _texttt(str(claim["representation_id"]))
        + " is " + _texttt(str(claim["representation_status"])) + ".",
    ]
    if claim["certificate_role"] is not None:
        provenance.append(
            "The certificate is offered as " + _texttt(str(claim["certificate_role"])) + "."
        )
    matrix = manuscript.verdict_matrix_for(claim_id)
    if matrix is not None:
        # ADR-0058 and ADR-0060 beside the claim rather than in an appendix a
        # reader may not reach: which reading set decided it, what the sweep
        # concluded, and how well the weakest reading in that set was read.
        convention = manuscript.convention_for(claim_id)
        status = manuscript.weakest_reading_status_for(claim_id)
        provenance.append(
            "Derived reading scope " + _texttt(str(manuscript.derived_scope(claim_id)))
            + " over the " + str(len(matrix.verdicts)) + " readings enumerated by "
            + _texttt(matrix.convention_id) + " (reading set "
            + _texttt(matrix.convention_hash) + "), recorded in "
            + _texttt(matrix.matrix_id) + "."
        )
        if status is not None:
            provenance.append(
                "The weakest reading it rests on is a "
                + READING_FIDELITY_WORDS[status] + "."
            )
        if convention is not None and convention.coupled_subject_ids:
            provenance.append(
                "A change to these readings also reaches "
                + ", ".join(_texttt(item) for item in convention.coupled_subject_ids)
                + ", whose recorded status this document does not change."
            )
    if classification.approved_axioms:
        provenance.append(
            "Approved axioms: "
            + ", ".join(_texttt(axiom) for axiom in classification.approved_axioms)
            + "."
        )
    if classification.unapproved_assumptions:
        provenance.append(
            "Unapproved assumptions: "
            + ", ".join(_texttt(name) for name in classification.unapproved_assumptions)
            + "."
        )
    rendered: list[str] = []
    for citation_id in claim["citations"]:
        text, citation_keys = _citation_text(manuscript, str(citation_id))
        rendered.append(text)
        keys.extend(citation_keys)
    if rendered:
        provenance.append("Background: " + "; ".join(rendered) + ".")
    original_problem = claim["original_problem_citation_id"]
    if original_problem is not None:
        problem_text, problem_keys = _citation_text(manuscript, str(original_problem))
        provenance.append("Original problem: " + problem_text + ".")
        keys.extend(problem_keys)
    lines.append(r"\adaprovenance{" + " ".join(provenance) + "}")
    lines.append(rf"\end{{{classification.environment}}}")
    authorship = claim["authorship"]
    if authorship["ai_generated"] is True:
        lines.append(
            r"\noindent{\footnotesize\textsf{Contribution.} This result was AI-generated by "
            + escape_prose(str(authorship["generator"]), f"{claim_id}.authorship.generator")
            + r".}\par"
        )
    derivation = claim["derivation"]
    lines.append(r"\paragraph{Auditable derivation.}")
    lines.append(escape_prose(str(derivation["summary"]), f"{claim_id}.derivation.summary"))
    derivation_citations: list[str] = []
    for citation_id in derivation["citations"]:
        text, citation_keys = _citation_text(manuscript, str(citation_id))
        derivation_citations.append(text)
        keys.extend(citation_keys)
    if derivation_citations:
        lines.append("Attribution and source influence: " + "; ".join(derivation_citations) + ".")
    if derivation["status"] == "unavailable":
        lines.append(
            r"\emph{No auditable derivation is available; this is an explicit limitation, "
            r"not an omitted proof.}"
        )
    if artifact is not None:
        relative = "lean/" + lean_artifact_filename(claim)
        status = str(artifact["verification_status"])
        lines.append(r"\adaformalartifact{status " + _texttt(status) + "}{" + relative + "}")
    if claim["lean_statement"] is not None:
        attestation_id = str(claim["attestation_id"]) if claim["attestation_id"] else "unattested"
        lines.append(r"\adaleanlabel{" + _texttt(attestation_id) + "}")
        statement = validate_verbatim(
            str(claim["lean_statement"]), f"{claim_id}.lean_statement"
        )
        lines.append(r"\begin{quote}\footnotesize\ttfamily\raggedright")
        lines.extend(escape_prose(line, f"{claim_id}.lean_statement.line") + r"\par" for line in statement.splitlines())
        lines.append(r"\end{quote}")
    return "\n".join(lines) + "\n\n", tuple(keys), classification


def _display_math(block: Mapping[str, Any]) -> str:
    caption = escape_prose(str(block["caption"]), f"{block['block_id']}.caption")
    return (
        r"\begin{equation*}" + "\n" + str(block["latex"]) + "\n" + r"\end{equation*}" + "\n"
        + (rf"\noindent{{\footnotesize {caption}}}" + "\n\n" if caption else "\n")
    )


def _certificate_table(manuscript: Manuscript, block: Mapping[str, Any]) -> str:
    certificate = manuscript.certificates[str(block["certificate_id"])]
    rows = [
        ("Case", str(certificate["case_id"])),
        ("Run", str(certificate["run_id"])),
        ("Engine", str(certificate["engine"])),
        ("Arithmetic", str(certificate["arithmetic"])),
        ("Floating point used", "no" if certificate["float_used"] is False else "yes"),
        ("Primal value", str(certificate["primal_value"])),
        ("Dual value", str(certificate["dual_value"])),
        ("Duality gap", str(certificate["gap"])),
        ("Classification", str(certificate["classification"])),
        ("Engine result hash", str(certificate["result_hash"])),
    ]
    body = " \\\\\n".join(
        f"{escape_prose(name, 'row')} & {_texttt(value)}" for name, value in rows
    )
    return (
        r"\begin{center}" + "\n" + r"\small\begin{tabular}{p{0.27\linewidth}p{0.65\linewidth}}" + "\n" + r"\hline" + "\n"
        + body + " \\\\\n" + r"\hline" + "\n" + r"\end{tabular}" + "\n"
        + r"\end{center}" + "\n\n"
    )


def _replay_index(manuscript: Manuscript) -> dict[str, Mapping[str, Any]]:
    """Replays addressable by either identity a verdict may cite."""

    index: dict[str, Mapping[str, Any]] = {}
    for replay in manuscript.replays.values():
        index[str(replay["result_hash"])] = replay
        index[str(replay["replay_id"])] = replay
    return index


def _replay_reading(
    replay: Mapping[str, Any] | None, reading_tuple: tuple[str, ...]
) -> tuple[str, str]:
    """The exact values a replay recorded for one reading, or their absence.

    ``not recorded`` is the honest answer, and it is never a zero, a blank cell,
    or a rounded number: a reading nobody evaluated must not read as an evaluated
    one, and no value in this projection is ever inexact.
    """

    if replay is None:
        return "not recorded", "not recorded"
    for reading in replay["readings"]:
        if tuple(str(item) for item in reading["reading"]) == reading_tuple:
            return str(reading["inverse_even"]), str(reading["range_value"])
    return "not recorded", "not recorded"


def _table(header: tuple[str, ...], rows: tuple[str, ...], layout: str) -> str:
    heading = " & ".join(
        r"\textbf{" + escape_prose(name, "table.header") + "}" for name in header
    )
    return (
        r"\begin{center}" + "\n" + r"\small\begin{tabular}{" + layout + "}" + "\n"
        + r"\hline" + "\n" + heading + " \\\\\n" + r"\hline" + "\n"
        + " \\\\\n".join(rows) + " \\\\\n" + r"\hline" + "\n"
        + r"\end{tabular}" + "\n" + r"\end{center}" + "\n\n"
    )


def reading_verdict_rows(manuscript: Manuscript) -> tuple[tuple[str, ...], ...]:
    """One row per (claim, enumerated reading): the derived fork, as data."""

    replays = _replay_index(manuscript)
    rows: list[tuple[str, ...]] = []
    for claim_id in sorted(manuscript.claims):
        matrix = manuscript.verdict_matrix_for(claim_id)
        if matrix is None:
            continue
        for verdict in sorted(matrix.verdicts, key=lambda item: item.reading_tuple):
            reading_tuple = tuple(verdict.reading_tuple)
            replay = replays.get(str(verdict.evidence_ref)) if verdict.evidence_ref else None
            inverse_even, range_value = _replay_reading(replay, reading_tuple)
            rows.append(
                (claim_id, ", ".join(reading_tuple), inverse_even, range_value, verdict.verdict)
            )
    return tuple(rows)


def _reading_verdict_block(manuscript: Manuscript) -> str:
    """ADR-0058's fork table. Derived, and no manuscript field can suppress it.

    A document whose result depends on a definitional choice displays the choice
    and its alternatives. The exact values are the ones an engine recorded against
    the reading in the same row; a reading with no replay behind it says so.
    """

    lines = [r"\section*{Readings and their verdicts}", ""]
    for claim_id in sorted(manuscript.claims):
        matrix = manuscript.verdict_matrix_for(claim_id)
        if matrix is None:
            continue
        status = manuscript.weakest_reading_status_for(claim_id)
        sentence = (
            "Claim " + _texttt(claim_id) + " is asserted over the readings enumerated by "
            + _texttt(matrix.convention_id) + ", and its derived scope is "
            + _texttt(str(manuscript.derived_scope(claim_id)))
            + ", computed from the verdicts below rather than supplied"
        )
        if status is not None:
            sentence += (
                ". The weakest reading it rests on is a " + READING_FIDELITY_WORDS[status]
            )
        lines.extend([sentence + ".", ""])
    rows = tuple(
        " & ".join(
            (
                _texttt(claim_id), _texttt(reading), _texttt(inverse_even),
                _texttt(range_value), _texttt(verdict),
            )
        )
        for claim_id, reading, inverse_even, range_value, verdict in reading_verdict_rows(
            manuscript
        )
    )
    lines.append(
        _table(
            ("Claim", "Reading", "InvEven", "Range", "Verdict"),
            rows,
            r"p{0.17\linewidth}p{0.25\linewidth}p{0.14\linewidth}p{0.17\linewidth}p{0.14\linewidth}",
        )
    )
    lines.extend([ENUMERATION_LIMIT_SENTENCE, ""])
    return "\n".join(lines) + "\n"


def counter_candidate_rows(manuscript: Manuscript) -> tuple[tuple[str, ...], ...]:
    """One row per (prior candidate, reading). A retrieved number is not a replay."""

    rows: list[tuple[str, ...]] = []
    for replay_id in sorted(manuscript.replays):
        replay = manuscript.replays[replay_id]
        if replay["citation_id"] is None:
            continue
        for reading in replay["readings"]:
            rows.append(
                (
                    str(replay["witness_graph_id"]),
                    ", ".join(str(item) for item in reading["reading"]),
                    str(reading["inverse_even"]),
                    str(reading["range_value"]),
                    str(reading["verdict"]),
                )
            )
    return tuple(rows)


def _counter_candidate_block(manuscript: Manuscript) -> str:
    """ADR-0059's replay table, derived and non-optional.

    Every row is the output of this repository's own exact engine on the prior
    candidate's witness, under every reading the convention enumerates. A number
    read off the earlier paper would not be a comparison, so none appears here.
    A replay whose ``citation_id`` is null is our own witness and discharges
    nothing, so it is not in this table.
    """

    lines = [r"\section*{Previously published candidates, replayed}", ""]
    for replay_id in sorted(manuscript.replays):
        replay = manuscript.replays[replay_id]
        if replay["citation_id"] is None:
            continue
        lines.extend([
            "Replay " + _texttt(replay_id) + " re-evaluated witness "
            + _texttt(str(replay["witness_graph_id"])) + " (spec "
            + _texttt(str(replay["witness_spec_hash"])) + ", order "
            + str(replay["order"]) + ") for citation "
            + _texttt(str(replay["citation_id"])) + " with engine "
            + _texttt(str(replay["engine"])) + " in "
            + _texttt(str(replay["arithmetic"])) + " arithmetic, floating point "
            + ("not used" if replay["float_used"] is False else "used") + ".",
            "",
        ])
    rows = tuple(
        " & ".join(
            (
                _texttt(witness), _texttt(reading), _texttt(inverse_even),
                _texttt(range_value), _texttt(verdict),
            )
        )
        for witness, reading, inverse_even, range_value, verdict in counter_candidate_rows(
            manuscript
        )
    )
    lines.append(
        _table(
            ("Witness", "Reading", "InvEven", "Range", "Verdict"),
            rows,
            r"p{0.13\linewidth}p{0.27\linewidth}p{0.16\linewidth}p{0.18\linewidth}p{0.14\linewidth}",
        )
    )
    lines.extend([
        "A replay records what an earlier witness does under each reading. It does not "
        "record what the earlier paper claims, and it decides no question of priority; "
        "priority stays an open obligation until a prior-art record closes it.",
        "",
    ])
    return "\n".join(lines) + "\n"


def _title_block(manuscript: Manuscript, headline: Headline) -> str:
    """The displayed title is the composed headline, escaped once and used twice.

    The PDF metadata title and the typeset title are the same derived string on
    purpose: a reader who copies the title out of a PDF viewer must get the
    qualified form, because the unqualified form is what a summary would keep.
    """

    value = manuscript.value
    authors = r" \and ".join(
        escape_prose(str(author["name"]), "author") + r"\thanks{"
        + escape_prose(str(author["role"]), "role") + "}"
        for author in value["authors"]
    )
    displayed = escape_prose(headline.displayed_title, "derived.title")
    return (
        r"\hypersetup{pdftitle={" + displayed
        + r"},pdfauthor={AdaIvy project},pdfsubject={AdaIvy record-driven mathematical report}}"
        + "\n" + r"\title{" + displayed + "}\n"
        + r"\author{" + authors + "}\n"
        + r"\date{}" + "\n" + r"\maketitle" + "\n\n"
    )


def _status_block(
    manuscript: Manuscript,
    classifications: tuple[EvidenceClassification, ...],
    headline: Headline,
) -> str:
    counts = {name: 0 for name in EVIDENCE_CLASSES}
    for classification in classifications:
        counts[classification.evidence_class] += 1
    kernel_checked_artifacts = sum(
        1
        for claim in manuscript.claims.values()
        if claim["lean_artifact"] is not None
        and claim["lean_artifact"]["verification_status"] == "kernel_checked"
    )
    if kernel_checked_artifacts == 0:
        lean_result = "No linked formal artifact has a recorded successful Lean kernel check."
    elif kernel_checked_artifacts == 1:
        lean_result = "Passed for one linked formal artifact."
    else:
        lean_result = f"Passed for {kernel_checked_artifacts} linked formal artifacts."
    formal_sentence = (
        lean_result
        + " A linked artifact can verify only part of a claim. AdaIvy labels a claim a "
        "Theorem only when its complete representation is kernel checked with no "
        "unapproved assumptions."
    )

    def counted(count: int, singular: str, plural: str | None = None) -> str:
        noun = singular if count == 1 else (plural or singular + "s")
        amount = "one" if count == 1 else "no" if count == 0 else str(count)
        return f"{amount} {noun}"
    approval = manuscript.value["publication_approval"]
    approval_sentence = (
        "No human publication approval record exists. Automated checks alone do not make "
        "this an endorsed AdaIvy result, so this document is a rendered projection and not "
        "an approved publication."
        if approval is None
        else "Publication approval " + _texttt(str(approval["approval_id"]))
        + " is recorded with " + _texttt(str(approval["authority"])) + " authority."
    )
    # ADR-0059. The classification is read from the manuscript's own prior-art
    # engagement record first, and only then from an approval. Keying this off
    # `publication_approval` is what left every draft reading `not_assessed`
    # while the records said otherwise, and drafts are what circulate.
    recheck = manuscript.prior_art_recheck()
    if recheck is None and approval is not None:
        recheck = load_recheck(approval["novelty_rechecks"][1])
    if recheck is None:
        prior_result_sentence = (
            "Prior-result classification: " + _texttt("not_assessed")
            + ". No prior-art engagement record and no pre-announcement classification "
            "are attached, so this document records no relationship to earlier work."
        )
    else:
        prior = recheck.classification()
        prior_result_sentence = (
            "Prior-result classification: " + _texttt(prior.report_classification)
            + "; target resolution status: " + _texttt(prior.target_resolution_status)
            + ", from re-check " + _texttt(recheck.recheck_id) + " at checkpoint "
            + _texttt(recheck.checkpoint) + " over subject "
            + _texttt(recheck.subject_id)
            + ". This relationship classification does not create mathematical warrant "
            "or a general novelty assessment."
        )
    toolchain = manuscript.value["toolchain"]
    lines = [
        r"\textbf{Lean verification.} " + formal_sentence,
        r"\par\smallskip",
        "Claim status: this report contains "
        + counted(counts["kernel_checked_theorem"], "fully Lean-verified Theorem") + ", "
        + counted(counts["exact_certificate_proposition"], "exact-certificate Proposition")
        + ", "
        + counted(
            counts["convention_relative_proposition"], "convention-relative Proposition"
        )
        + ", and "
        + counted(counts["proposal"], "unresolved or conjectural Proposal") + ".",
        r"\par\smallskip",
        "Environment names are computed from the records that back each claim; no input "
        "field selects one, and every missing record weakens the rendered claim rather "
        "than strengthening it.",
        r"\par\smallskip",
        "Novelty: " + _texttt(str(manuscript.value["novelty"]["status"]))
        + ". Significance: " + _texttt(str(manuscript.value["significance"]["status"]))
        + ". Neither is inferred from any proof status, and no automated assessment of "
        "either exists in this system.",
        r"\par\smallskip",
        prior_result_sentence,
        r"\par\smallskip",
        "Corpus provenance: " + _texttt(str(manuscript.value["corpus_provenance"]))
        + ". " + approval_sentence,
        r"\par\smallskip",
        "Formal backend pinned at Lean " + _texttt(str(toolchain["lean_version"]))
        + " commit " + _texttt(str(toolchain["lean_commit"])[:12])
        + ", mathlib " + _texttt(str(toolchain["mathlib_version"]))
        + " commit " + _texttt(str(toolchain["mathlib_commit"])[:12]) + ".",
        r"Every solved claim has a linked \texttt{.lean} artifact. File creation is not "
        r"formal verification; each link states \texttt{pending}, \texttt{failed}, or "
        r"\texttt{kernel\_checked} from its record.",
    ]
    # ADR-0058. The displayed title is a derived string, so the reader is told
    # what derived it and that nothing in the record set could have selected it.
    lines.extend([
        r"\par\smallskip",
        "Displayed title: " + escape_prose(headline.title_stem, "headline.stem")
        + " plus a derived qualifier"
        + (
            " (" + "; ".join(
                escape_prose(item, "headline.qualifier") for item in headline.qualifiers
            ) + ")"
            if headline.qualifiers
            else ", which these records leave empty"
        )
        + ". The qualifier is computed from "
        + "; ".join(escape_prose(item, "headline.derivation") for item in headline.derivation)
        + ". No manuscript field selects it. A missing record adds hedging to the "
        "qualifier rather than removing it, so it weakens the displayed claim.",
    ])
    if manuscript.verdict_matrices:
        scope_sentences = []
        for claim_id in sorted(manuscript.claims):
            matrix = manuscript.verdict_matrix_for(claim_id)
            if matrix is None:
                continue
            status = manuscript.weakest_reading_status_for(claim_id)
            scope_sentences.append(
                _texttt(claim_id) + " is " + _texttt(str(manuscript.derived_scope(claim_id)))
                + " over the readings enumerated by " + _texttt(matrix.convention_id)
                + (
                    ", resting on a " + READING_FIDELITY_WORDS[status]
                    if status is not None
                    else ""
                )
            )
        lines.extend([
            r"\par\smallskip",
            "Derived reading scope: " + "; ".join(scope_sentences) + ". "
            + ENUMERATION_LIMIT_SENTENCE,
        ])
    if manuscript.conventions:
        lines.extend([
            r"\par\smallskip",
            (
                "Source fidelity: every reading this document enumerates is "
                "verbatim-confirmed against a passage a reader can re-extract."
                if manuscript.every_reading_is_confirmed()
                else "Source fidelity: at least one enumerated reading is not "
                "verbatim-confirmed, either because nobody re-extracted the passage or "
                "because its rights forbid reproducing it here. No claim in this "
                "document is described as source-faithful, and that phrase is earned "
                "from reading statuses rather than asserted."
            ),
        ])
    return r"\adastatusblock{" + "\n" + "\n".join(lines) + "\n}" + "\n\n"


def _abstract_block(manuscript: Manuscript) -> str:
    return (
        r"\begin{abstract}" + "\n"
        + escape_prose(str(manuscript.value["abstract"]), "abstract") + "\n"
        + r"\end{abstract}" + "\n\n"
    )


def _run_disclosure_block(manuscript: Manuscript) -> str:
    disclosure = manuscript.value["run_disclosure"]
    models = "; ".join(
        escape_prose(str(item["provider"]), "run.provider") + " / "
        + _texttt(str(item["model"])) + " ("
        + str(item["calls"]) + " request(s) attempted; "
        + escape_prose(str(item["outcome"]), "run.outcome") + ")"
        for item in disclosure["models"]
    )
    def shown(key: str, suffix: str = "") -> str:
        item = disclosure[key]
        return "not recorded" if item is None else f"{item}{suffix}"
    return (
        r"\section*{Run disclosure}" + "\n\n"
        + "Recorded model activity: " + models + ". "
        + "Recorded model calls: " + shown("model_calls") + ". "
        + "Recorded estimated model cost: USD " + shown("cost_usd")
        + " (authorized cap USD " + shown("budget_cap_usd") + "). "
        + "Recorded tokens: " + shown("input_tokens") + " input, "
        + shown("output_tokens") + " output, " + shown("total_tokens") + " total. "
        + "Measurement status: " + _texttt(str(disclosure["measurement_status"])) + ". "
        + escape_prose(str(disclosure["note"]), "run.note") + "\n\n"
    )


def _axioms_appendix(manuscript: Manuscript) -> str:
    if not manuscript.attestations:
        return (
            r"\section*{Appendix A. Axiom dependence}" + "\n\n"
            + "No formal attestation is bound to this document, so no declaration, axiom "
            + "list, or kernel outcome is reportable. Linked Lean artifacts may still be "
            + "present with pending status; file creation is not a kernel result.\n\n"
        )
    rows = []
    for attestation_id in sorted(manuscript.attestations):
        attestation = manuscript.attestations[attestation_id]
        rows.extend([
            r"Declaration & " + _texttt(str(attestation["declaration_name"])) + r" \\",
            r"Outcome & " + _texttt(str(attestation["outcome"])) + r" \\",
            r"Approved axioms & "
            + (", ".join(_texttt(axiom) for axiom in attestation["approved_axioms"]) or "none")
            + r" \\",
            r"Unapproved assumptions & "
            + (", ".join(_texttt(name) for name in attestation["unapproved_assumptions"]) or "none")
            + r" \\",
            r"\hline",
        ])
    body = "\n".join(rows)
    return (
        r"\section*{Appendix A. Axiom dependence}" + "\n\n"
        + "Each row is the recorded output of a kernel check plus its "
        + r"\texttt{\#print axioms} " + "result, against the pinned toolchain named in the "
        + "status block.\n\n"
        + r"\begin{center}" + "\n"
        + r"\small\begin{tabular}{p{0.27\linewidth}p{0.65\linewidth}}" + "\n"
        + r"\hline" + "\n" + body + "\n"
        + r"\end{tabular}" + "\n" + r"\end{center}" + "\n\n"
    )


def _obligations_appendix(manuscript: Manuscript) -> str:
    if not manuscript.obligations:
        return (
            r"\section*{Appendix B. Open obligations}" + "\n\n"
            + "No obligation record exists for this document.\n\n"
        )
    items = []
    for obligation_id in sorted(manuscript.obligations):
        obligation = manuscript.obligations[obligation_id]
        items.append(
            r"\item[" + _texttt(obligation_id) + "] "
            + escape_prose(str(obligation["statement"]), "statement")
            + " Status " + _texttt(str(obligation["status"])) + ". "
            + escape_prose(str(obligation["reason"]), "reason")
        )
    return (
        r"\section*{Appendix B. Open obligations}" + "\n\n"
        + "Background this document relies on but holds no record for appears here rather "
        + "than in the bibliography. An unrecorded reference is an open obligation, not a "
        + "citation.\n\n"
        + r"\begin{description}" + "\n" + "\n".join(items) + "\n" + r"\end{description}" + "\n\n"
    )


def _provenance_appendix(manuscript: Manuscript) -> str:
    return (
        r"\section*{Appendix C. Reproduction}" + "\n\n"
        + "This document is a projection of manuscript "
        + _texttt(manuscript.manuscript_id) + " with content hash "
        + _texttt(manuscript.hash) + ", rendered against template "
        + _texttt(TEMPLATE_HASH) + ". The bundle accompanying this document carries the "
        + "records the projection read, the Lean source for every solved claim, and a "
        + "manifest hashing every file. A document cannot contain its own hash, so the "
        + "rendered document hash and the bundle hash are recorded in "
        + _texttt("MANIFEST.json") + " rather than here.\n\n"
    )


def _bibliography_block(entries: tuple[BibliographyEntry, ...]) -> str:
    if not entries:
        return ""
    widest = max(len(entry.key) for entry in entries)
    items = []
    for entry in entries:
        fields = dict(entry.fields)
        items.append(
            r"\bibitem{" + entry.key + "} "
            + fields.get("author", "")
            + ", \\emph{" + fields.get("title", "") + "}, "
            + ", ".join(
                value for name, value in entry.fields
                if name not in {"author", "title"} and value
            )
            + "."
        )
    return (
        r"\begin{thebibliography}{" + "9" * min(widest, 2) + "}" + "\n"
        + "\n".join(items) + "\n" + r"\end{thebibliography}" + "\n\n"
    )


def _project_footnote() -> str:
    return (
        r"\par\bigskip\noindent\emph{About this project}\footnote{" +
        "AdaIvy is an open-source AI-assisted mathematical research project that keeps "
        "retrieval, computation, formal checking, human review, and publication status "
        "as separate recorded boundaries. Source code and reproducibility materials: "
        r"\url{" + ADAIvy_GITHUB_URL + r"}.}" + "\n\n"
    )


def render_manuscript(manuscript: Manuscript) -> RenderedDocument:
    ledger: list[LedgerBlock] = []
    classifications: list[EvidenceClassification] = []
    cite_keys: list[str] = []
    manuscript_id = manuscript.manuscript_id
    namespace = set(manuscript.record_ids) | {manuscript_id}

    def add(block_id: str, origin: str, refs: tuple[str, ...], tex: str) -> None:
        if not refs:
            raise PublicationValidationError(
                "block_without_record_ref", f"derived block {block_id} carries no record reference"
            )
        for ref in refs:
            if ref not in namespace:
                raise PublicationValidationError(
                    "record_ref_unresolved", f"block {block_id} references {ref!r}"
                )
        ledger.append(LedgerBlock(block_id=block_id, origin=origin, record_refs=refs, tex=tex))

    # The headline reads the evidence classes, and the evidence classes are a
    # pure function of the manuscript, so they are computed before the first
    # block is emitted rather than patched in afterwards. That keeps the title
    # block inside `add`, which is where record references are checked to
    # resolve: a derived title outside reference checking is the original defect.
    headline = compose_headline(
        manuscript,
        tuple(
            classify_claim(manuscript, str(block["claim_id"]))
            for section in manuscript.value["sections"]
            for block in section["blocks"]
            if block["kind"] == "claim"
        ),
    )
    add("derived.title", "derived", headline.record_refs, _title_block(manuscript, headline))

    # The status block is emitted here, before any section, and no manuscript
    # field can remove it: it is produced by the renderer rather than read from
    # the sections list. It is appended after classification below, so it is
    # inserted as a placeholder index and rewritten once the classes are known.
    status_index = len(ledger)
    ledger.append(
        LedgerBlock(block_id="derived.status", origin="derived", record_refs=(manuscript_id,), tex="")
    )
    add("derived.abstract", "derived", (manuscript_id,), _abstract_block(manuscript))
    add("derived.run-disclosure", "derived", (manuscript_id,), _run_disclosure_block(manuscript))

    # ADR-0058 and ADR-0059. Both tables are derived and neither is selectable:
    # they appear whenever the records that populate them exist, ahead of the
    # body, so the fork and the prior candidate's fate reach a reader who stops
    # after the first page.
    if manuscript.verdict_matrices:
        refs = tuple(sorted(
            set(manuscript.verdict_matrices)
            | {matrix.convention_id for matrix in manuscript.verdict_matrices.values()}
            | {matrix.claim_id for matrix in manuscript.verdict_matrices.values()}
        ))
        add("derived.reading-verdicts", "derived", refs, _reading_verdict_block(manuscript))
    prior_candidates = tuple(sorted(
        replay_id for replay_id, replay in manuscript.replays.items()
        if replay["citation_id"] is not None
    ))
    if prior_candidates:
        refs = prior_candidates + tuple(sorted({
            str(manuscript.replays[replay_id]["citation_id"]) for replay_id in prior_candidates
        }))
        add("derived.counter-candidate-replays", "derived", refs, _counter_candidate_block(manuscript))

    for section in manuscript.value["sections"]:
        section_refs: list[str] = []
        rendered_blocks: list[tuple[str, tuple[str, ...], str]] = []
        for block in section["blocks"]:
            block_id = str(block["block_id"])
            refs = tuple(str(ref) for ref in block["record_refs"])
            section_refs.extend(refs)
            if block["kind"] == "prose":
                tex, keys = _prose(manuscript, block)
                cite_keys.extend(keys)
            elif block["kind"] == "claim":
                tex, keys, classification = _claim(manuscript, block)
                cite_keys.extend(keys)
                classifications.append(classification)
            elif block["kind"] == "display_math":
                tex = _display_math(block)
            else:
                tex = _certificate_table(manuscript, block)
            rendered_blocks.append((block_id, refs, tex))
        heading = (
            r"\section{" + escape_prose(str(section["title"]), "section.title") + "}" + "\n\n"
        )
        add(f"derived.heading.{section['section_id']}", "derived", tuple(section_refs), heading)
        for block_id, refs, tex in rendered_blocks:
            add(block_id, "manuscript", refs, tex)

    ledger[status_index] = LedgerBlock(
        block_id="derived.status", origin="derived",
        record_refs=tuple(sorted({item.claim_id for item in classifications}) or (manuscript_id,)),
        tex=_status_block(manuscript, tuple(classifications), headline),
    )

    add(
        "derived.appendix.axioms", "derived",
        tuple(sorted(manuscript.attestations)) or (manuscript_id,),
        _axioms_appendix(manuscript),
    )
    add(
        "derived.appendix.obligations", "derived",
        tuple(sorted(manuscript.obligations)) or (manuscript_id,),
        _obligations_appendix(manuscript),
    )
    add("derived.appendix.reproduction", "derived", (manuscript_id,), _provenance_appendix(manuscript))

    entries = build_bibliography(manuscript)
    verify_citation_closure(manuscript, entries, tuple(cite_keys))
    if entries:
        add(
            "derived.bibliography", "derived",
            tuple(sorted(entry.source_id for entry in entries)),
            _bibliography_block(entries),
        )

    add("derived.project-footnote", "derived", (manuscript_id,), _project_footnote())

    tex = TEMPLATE_HEAD + "".join(block.tex for block in ledger) + TEMPLATE_TAIL
    counts = {name: 0 for name in EVIDENCE_CLASSES}
    for classification in classifications:
        counts[classification.evidence_class] += 1
    statistics = {
        "blocks": len(ledger),
        "manuscript_blocks": sum(1 for block in ledger if block.origin == "manuscript"),
        "derived_blocks": sum(1 for block in ledger if block.origin == "derived"),
        "claims": len(classifications),
        "evidence_class_counts": counts,
        "bibliography_entries": len(entries),
        "cite_keys": len(set(cite_keys)),
        "obligations_open": sum(
            1 for obligation in manuscript.obligations.values() if obligation["status"] == "open"
        ),
        "tex_bytes": len(tex.encode("utf-8")),
    }
    document = RenderedDocument(
        manuscript_id=manuscript_id, manuscript_hash=manuscript.hash,
        template_hash=TEMPLATE_HASH, document_hash=text_hash(tex), headline=headline, tex=tex,
        ledger=tuple(ledger), classifications=tuple(classifications), bibliography=entries,
        cite_keys=tuple(sorted(set(cite_keys))), statistics=statistics,
    )
    verify_ledger_closure(document)
    verify_headline_closure(document)
    return document


def verify_headline_closure(document: RenderedDocument) -> None:
    """Refuse a document whose displayed title the ledger does not account for.

    Amendment A6. A derived title that lives outside the provenance ledger is the
    original defect in new clothes: the one reader-facing string with no record
    behind it. So the composed headline is checked three ways -- it is in the
    ledger, it is in the block the ledger says carries it, and that block cites
    the records the composition read -- and every one of those is a refusal.
    """

    blocks = [block for block in document.ledger if block.block_id == "derived.title"]
    if len(blocks) != 1:
        raise PublicationValidationError(
            "headline_not_in_ledger",
            f"{len(blocks)} ledger blocks carry the derived title; exactly one must",
        )
    block = blocks[0]
    displayed = escape_prose(document.headline.displayed_title, "derived.title")
    if displayed not in block.tex:
        raise PublicationValidationError(
            "headline_not_in_ledger",
            "the derived title block does not contain the composed headline, so the "
            "displayed title is not covered by ledger closure",
        )
    if displayed not in document.tex:
        raise PublicationValidationError(
            "headline_not_in_ledger",
            "the document does not display the composed headline",
        )
    missing = sorted(set(document.headline.record_refs) - set(block.record_refs))
    if missing:
        raise PublicationValidationError(
            "headline_record_refs_incomplete",
            f"the derived title was composed from {missing} but the ledger block does not "
            "cite them; a qualifier with no resolving reference cannot be audited",
        )


def verify_ledger_closure(document: RenderedDocument) -> None:
    """Refuse a document that is not exactly template plus ledger."""

    for block in document.ledger:
        if not block.record_refs:
            raise PublicationValidationError(
                "block_without_record_ref", f"ledger block {block.block_id} carries no reference"
            )
    recomputed = TEMPLATE_HEAD + "".join(block.tex for block in document.ledger) + TEMPLATE_TAIL
    if recomputed != document.tex:
        raise PublicationValidationError(
            "ledger_closure_broken",
            "the document is not exactly the frozen template plus the ledger blocks",
        )
    if document.document_hash != text_hash(document.tex):
        raise PublicationValidationError(
            "document_hash_mismatch", "the recorded document hash does not cover the document"
        )
    if document.template_hash != TEMPLATE_HASH:
        raise PublicationValidationError(
            "template_hash_mismatch", "the document was rendered against a different template"
        )


def ledger_payload(document: RenderedDocument) -> dict[str, Any]:
    return {
        "manuscript_id": document.manuscript_id,
        "manuscript_hash": document.manuscript_hash,
        "template_hash": document.template_hash,
        "document_hash": document.document_hash,
        "headline": {
            "title_stem": document.headline.title_stem,
            "resolution_phrase": document.headline.resolution_phrase,
            "qualifiers": list(document.headline.qualifiers),
            "displayed_title": document.headline.displayed_title,
            "record_refs": list(document.headline.record_refs),
            "derivation": list(document.headline.derivation),
            "creates_mathematical_warrant": False,
        },
        "blocks": [
            {
                "block_id": block.block_id,
                "origin": block.origin,
                "record_refs": list(block.record_refs),
                "block_hash": block.block_hash,
                "bytes": len(block.tex.encode("utf-8")),
            }
            for block in document.ledger
        ],
    }
